### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by josifbg** [gravitl/netmaker-ui-2#215]
Describe what happened...

 Error log: 
`NotFoundGraphError: Graph.addEdge: target node "997cfd9a-daaf-4559-ad0a-d37d44d87689" not found.
{
    "componentStack": "\n    at fRe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:880:64372)\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:880:41675\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:394:7030\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:394:9006\n    at div\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:377:5627\n    at n (https://dashboard.vp.benzona.org/assets/index-559417fc.js:94:1085)\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:94:5784\n    at div\n    at div\n    at kpe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:377:6007)\n    at div\n    at Qpe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:377:20342)\n    at S7 (https://dashboard.vp.benzona.org/assets/index-559417fc.js:379:8622)\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:394:7030\n    at div\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:394:9006\n    at _p (https://dashboard.vp.benzona.org/assets/index-559417fc.js:377:4462)\n    at main\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:230:67254\n    at M8e (https://dashboard.vp.benzona.org/assets/index-559417fc.js:889:17925)\n    at sc (https://dashboard.vp.benzona.org/assets/index-559417fc.js:889:79232)\n    at CCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:3878)\n    at jCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:7404)\n    at main\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:230:67254\n    at section\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:230:67554\n    at section\n    at https://dashboard.vp.benzona.org/assets/index-559417fc.js:230:67554\n    at Fv (https://dashboard.vp.benzona.org/assets/index-559417fc.js:624:269)\n    at A4e (https://dashboard.vp.benzona.org/assets/index-559417fc.js:624:28493)\n    at CCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:3878)\n    at SCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:3142)\n    at PCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:7053)\n    at kCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:7442)\n    at TCe (https://dashboard.vp.benzona.org/assets/index-559417fc.js:592:6203)\n    at nee (https://dashboard.vp.benzona.org/assets/index-559417fc.js:94:9630)\n    at dee (https://dashboard.vp.benzona.org/assets/index-559417fc.js:94:10893)\n    at fp (https://dashboard.vp.benzona.org/assets/index-559417fc.js:94:13899)\n    at div\n    at q8e (https://dashboard.vp.benzona.org/assets/index-559417fc.js:889:115580)"
}`

**Comment by Aceix** [comment]
@josifbg does this error clear when you refresh the browser?

**Comment by Aceix** [comment]
crash has been fixed. issue should be resolved in the next release
