### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by jafarijason** [gravitl/netmaker-ui-2#305]
Describe what happened...

 Error log: 
`NotFoundGraphError: Graph.addEdge: target node "5fd04cc5-955e-4f39-be65-d3434245ce1c" not found.
{
    "componentStack": "\n    at gRe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:880:64372)\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:880:41675\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:394:7030\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:394:9006\n    at div\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:377:5627\n    at n (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:94:1085)\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:94:5784\n    at div\n    at div\n    at Fpe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:377:6007)\n    at div\n    at nme (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:377:20342)\n    at EA (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:379:8622)\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:394:7030\n    at div\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:394:9006\n    at Ip (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:377:4462)\n    at main\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:230:67254\n    at L8e (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:889:17925)\n    at _Ce (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:3878)\n    at ACe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:7404)\n    at main\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:230:67254\n    at section\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:230:67554\n    at section\n    at https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:230:67554\n    at Cw (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:624:277)\n    at H4e (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:624:7309)\n    at _Ce (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:3878)\n    at OCe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:3142)\n    at DCe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:7053)\n    at FCe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:7442)\n    at kCe (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:592:6203)\n    at aee (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:94:9638)\n    at mee (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:94:10901)\n    at pp (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:94:13907)\n    at div\n    at Z8e (https://app.netmaker.io/v0.20.5/assets/index-46330ac4.js:889:115640)"
}`

**Comment by Aceix** [comment]
cant reproduce. also, further checks have been added in the latest version of the ui.
please feel free to re-open if this happens again
