### ISSUE TITLE
[Bug]: UI form for DNS entries only allow TLDs with up to 6 characters

### ISSUE THREAD

**Issue by brunobriante** [gravitl/netmaker-ui-2#402]
Currently the modal for DNS entries has a regex allowing only 2 to 6 characters in the TLD of an entry ([regexline](https://github.com/gravitl/netmaker-ui-2/blob/b305a96fc19160346f7cd59439d4625f262aaedf/src/components/modals/add-dns-modal/AddDnsModal.tsx#L75)). This is not a validation that is made on the API itself, only on the frontend.

Based on the [tld list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) maintained by IANA (which i got from [ICANN](https://www.icann.org/resources/pages/tlds-2012-02-25-en)) a TLD currently can have up to 24 characters and has  P99 of ~15.48. 

![download](https://github.com/gravitl/netmaker-ui-2/assets/265922/b3854341-2763-49d2-8bf7-6a71ce40318d)

Currently i can't manage some of my domains (which are using the .service TLD) via the UI because of that. Can this regex be altered to a value that allow those longer TLDs or even up to 63 characters as per RFC-1123?

**Comment by Aceix** [comment]
thanks for raising this issue @brunobriante. we'll definitely consider this

**Comment by Aceix** [comment]
actually, this should be resolved in the next release. we already made the validation a bit looser since other users encoutered this issue
ref: https://github.com/gravitl/netmaker-ui-2/blob/develop/src/components/modals/add-dns-modal/AddDnsModal.tsx
