### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by chukfinley** [gravitl/netmaker-ui-2#413]
Describe what happened...

 Error log: 
`TypeError: s is null
{
    "componentStack": "\nS_e<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:780:41667\ndiv\nwhe<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:344:7095\ndiv\nChe<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:344:8983\ndiv\ndiv\nv7<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:327:6571\nn@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:94:7616\nnee/r<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:94:12301\ndiv\ndiv\nGde@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:327:6951\ndiv\ndfe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:327:21676\nS7@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:329:8898\ndiv\nwhe<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:344:7095\ndiv\nChe<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:344:8983\nsp@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:327:5123\nmain\nr3<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:378:46682\nDTe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:780:100168\nwCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:3900\nPCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:7402\nmain\nr3<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:378:46682\ndiv\nQge<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:378:46945\ndiv\nQge<@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:378:46945\nDx@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:524:277\nWIe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:524:5775\nwCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:3900\nxCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:3142\n_Ce@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:7064\njCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:7524\nNCe@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:479:6224\ncee@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:94:16228\nvee@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:94:18029\nYh@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:94:20815\ndiv\nl5e@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:780:249578\ni5e@https://dashboard.netmaker.chuk.dev/assets/index-4c1d51e2.js:780:246632"
}`

**Comment by Aceix** [comment]
hello @chukfinley. can you briefly describe what led to this error? and the UI version you were using

**Comment by Aceix** [comment]
closing as stale issue. stability fixes are pushed with releases
