### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by luoshaocn** [gravitl/netmaker-ui-2#448]
Describe what happened...

 Error log: 
`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
{
    "componentStack": "\n    at span\n    at button\n    at _ne (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:167:31165)\n    at gre (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:167:48185)\n    at div\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at div\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:344:8913\n    at div\n    at b3 (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:62:131)\n    at HA (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:182:43997)\n    at div\n    at div\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:1647\n    at div\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:1810\n    at n (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:94:7630)\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:94:12337\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:3559\n    at div\n    at div\n    at _re (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:4609)\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:278\n    at N3 (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:171:6631)\n    at kg (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:182:43032)\n    at Dd (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:167:33643)\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at GI (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:512:18765)\n    at main\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:378:46660\n    at Gje (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:846:95849)\n    at ru (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:846:109394)\n    at l2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:479:3944)\n    at v2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:479:7091)\n    at main\n    at https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:378:46660\n    at div\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at div\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at WIe (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:522:5774)\n    at l2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:479:3944)\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at k2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:488:4534)\n    at y2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:479:7129)\n    at j2e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:488:1875)\n    at Xee (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:94:16260)\n    at rte (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:94:17318)\n    at js (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:40:27469)\n    at div\n    at g5e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:846:162007)\n    at h5e (https://dashboard.mps11mps.eu.org/assets/index-730d9a62.js:846:158734)"
}`

**Comment by Aceix** [comment]
closing as stale issue. stability fixes are pushed with releases
