### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by fitzgeraldtech** [gravitl/netmaker-ui-2#494]
Describe what happened...

 Error log: 
`TypeError: Cannot read properties of null (reading 'blendFunc')
{
    "componentStack": "\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:778:41675\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:344:7095\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:344:8913\n    at div\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:327:6573\n    at n (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:94:7630)\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:94:12335\n    at div\n    at div\n    at Kfe (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:327:6953)\n    at div\n    at dhe (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:327:21678)\n    at y9 (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:329:8749)\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:344:7095\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:344:8913\n    at Hm (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:327:5008)\n    at main\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:378:46662\n    at V6e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:846:48096)\n    at L2e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:479:3944)\n    at G2e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:479:7091)\n    at main\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:378:46662\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:378:46962\n    at div\n    at https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:378:46962\n    at xw (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:522:277)\n    at _Ne (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:522:5774)\n    at L2e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:479:3944)\n    at A2e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:479:3183)\n    at cEe (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:488:4534)\n    at K2e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:479:7129)\n    at lEe (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:488:1875)\n    at lte (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:94:16258)\n    at gte (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:94:17316)\n    at Im (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:94:20853)\n    at div\n    at y5e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:846:218248)\n    at p5e (https://dashboard.netmaker.fitzgeraldtech.com/assets/index-d7ec8238.js:846:214966)"
}`

**Comment by Aceix** [comment]
closing as a one-timer. stability patches are pushed per-release. will also add more meaningful default logs
