### ISSUE TITLE
Img request to freepik is leaking referer

### ISSUE THREAD

**Issue by FallingSnow** [gravitl/netmaker-ui-2#52]
Not a big deal but in my opinion a security focused application should not be making requests to uncontrolled 3rd parties. This images sources should be served from the dashboard's included assets.

https://github.com/gravitl/netmaker-ui-2/blob/5765dc8b2368b9ec616d2428ad474e2528a2bd38/src/layouts/MainLayout.tsx#L229-L234

By leaking I mean it sends the referrer.
![Screenshot from 2023-05-26 13-39-41](https://github.com/gravitl/netmaker-ui-2/assets/2512197/6d8b8484-814d-431d-875c-157f0831bc04)

**Comment by Aceix** [comment]
fixed with https://github.com/gravitl/netmaker-ui-2/pull/53

**Comment by Aceix** [comment]
Thanks again @FallingSnow
